--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		bg = 1,
		headImage = 2,
		IDLabel = 3,
		sexImage = 4,
		nameLabel = 5,
		levelImage = 6,
		moneyLabel = 7,
		levelLabel = 8,
		generalNumLabel = 9,
		maxWinLabel = 10,
		winRateLabel = 11,
		addDeleteButton = 12,
		addDeleteLabel = 13,
		giftButton = 14,
		giftLabel = 15,
		trackButton = 16,
		trackLabel = 17,
		statusLabel = 18,
	},
	ui = {
		[1] = {"bg"},
		[2] = {"bg","headBg","headImage"},
		[3] = {"bg","IDLabel"},
		[4] = {"bg","sexImage"},
		[5] = {"bg","nameLabel"},
		[6] = {"bg","levelImage"},
		[7] = {"bg","moneyLabel"},
		[8] = {"bg","levelLabel"},
		[9] = {"bg","generalNumLabel"},
		[10] = {"bg","maxWinLabel"},
		[11] = {"bg","winRateLabel"},
		[12] = {"bg","btnsBg","addDeleteButton"},
		[13] = {"bg","btnsBg","addDeleteButton","addDeleteLabel"},
		[14] = {"bg","btnsBg","giftButton"},
		[15] = {"bg","btnsBg","giftButton","giftLabel"},
		[16] = {"bg","btnsBg","trackButton"},
		[17] = {"bg","btnsBg","trackButton","trackLabel"},
		[18] = {"bg","statusLabel"},
	},
	func = {
		[1] = "onPopupBgTouch",
		[12] = "onAddDeleteButtonClick",
		[14] = "onGiftButtonClick",
		[16] = "onTrackButtonClick",
	},
}
return MAP;