local fans_layer=
{
	name="fans_layer",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="Image_bg",type=1,typeName="Image",time=0,x=0,y=0,width=710,height=517,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_popup_bg_big.png",varname="Image_bg",callbackfunc="onPopupBgTouch",
		{
			name="Image4",type=1,typeName="Image",time=0,x=183,y=2,width=326,height=77,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_pop_bg_title.png",gridLeft=150,gridRight=150,gridTop=35,gridBottom=35,
			{
				name="Text_title",type=4,typeName="Text",time=0,x=85,y=20,width=162,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=30,textAlign=kAlignCenter,colorRed=250,colorGreen=230,colorBlue=255,string=[[Text]],colorA=1,varname="Text_title"
			}
		},
		{
			name="Image6",type=1,typeName="Image",time=0,x=35,y=101,width=475,height=53,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/freeGold/freeGold_input.png",gridLeft=15,gridRight=15,gridTop=20,gridBottom=20,
			{
				name="EditText_code",type=6,typeName="EditText",time=0,x=12,y=7,width=449,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=90,colorGreen=70,colorBlue=120,colorA=1,varname="EditText_code"
			}
		},
		{
			name="Image8",type=1,typeName="Image",time=0,x=26,y=165,width=660,height=260,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/freeGold/freeGold_di.png",gridLeft=15,gridRight=15,gridTop=20,gridBottom=20,
			{
				name="TextView_content",type=5,typeName="TextView",time=0,x=350,y=29,width=280,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignTopLeft,colorRed=190,colorGreen=160,colorBlue=225,string=[[TextView]],colorA=1,varname="TextView_content"
			},
			{
				name="TextView_url",type=5,typeName="TextView",time=0,x=350,y=151,width=280,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignTopLeft,colorRed=145,colorGreen=200,colorBlue=255,string=[[TextView]],colorA=1,varname="TextView_url"
			},
			{
				name="Image11",type=1,typeName="Image",time=0,x=5,y=60,width=293,height=184,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/freeGold/freeGold_gift.png"
			}
		},
		{
			name="Button_code",type=1,typeName="Button",time=0,x=537,y=94,width=143,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_btn_yellow_m.png",gridLeft=40,gridRight=40,callbackfunc="bt_code_click",varname="Button_code",
			{
				name="Text_bt_code",type=4,typeName="Text",time=0,x=20,y=13,width=100,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_bt_code",colorA=1
			}
		},
		{
			name="Button_fans",type=1,typeName="Button",time=0,x=215,y=421,width=272,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/freeGold/freeGold_bt.png",varname="Button_fans",callbackfunc="bt_fans_click",
			{
				name="Text_bt_link",type=4,typeName="Text",time=0,x=35,y=16,width=203,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="Text_bt_link"
			}
		}
	}
}
return fans_layer;