local rank_rule_pop_layer=
{
	name="rank_rule_pop_layer",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=0,x=0,y=0,width=710,height=517,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_pop_bg.png",callbackfunc="onPopupBgTouch",varname="bg",
		{
			name="tabBg",type=1,typeName="Image",time=0,x=2,y=19,width=355,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_tab_bg.png",gridLeft=30,gridRight=30,
			{
				name="radioButtonGroup",type=0,typeName="RadioButtonGroup",time=0,x=0,y=1,width=355,height=50,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,varname="radioButtonGroup",
				{
					name="awardRadiobutton",type=0,typeName="RadioButton",time=0,x=0,y=0,width=190,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/common/common_transparent.png",file2="res/common/common_btn_left.png",varname="awardRadiobutton",
					{
						name="titleAwardLabel",type=4,typeName="Text",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[每日牌局榜]],varname="titleAwardLabel"
					}
				},
				{
					name="ruleRadiobutton",type=0,typeName="RadioButton",time=0,x=0,y=0,width=190,height=62,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/common/common_transparent.png",file2="res/common/common_btn_right.png",varname="ruleRadiobutton",
					{
						name="titleRuleLabel",type=4,typeName="Text",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[规则]],varname="titleRuleLabel"
					}
				}
			}
		},
		{
			name="closeButton",type=1,typeName="Button",time=0,x=17,y=14,width=51,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_close_btn.png",varname="closeButton",callbackfunc="onCloseButtonClick"
		}
	},
	{
		name="comtentBg",type=1,typeName="Image",time=0,x=0,y=160,width=670,height=382,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/rank/rank_sub_bg.png",gridLeft=15,gridRight=15,gridTop=15,gridBottom=15,varname="comtentBg",
		{
			name="contentRankLabel",type=4,typeName="Text",time=0,x=72,y=15,width=100,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=246,colorGreen=183,colorBlue=1,string=[[Ranking]],varname="contentRankLabel",colorA=1
		},
		{
			name="contentAwardLabel",type=4,typeName="Text",time=0,x=417,y=15,width=100,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=246,colorGreen=183,colorBlue=1,string=[[Hadiah]],varname="contentAwardLabel",colorA=1
		},
		{
			name="awardListView",type=0,typeName="ListView",time=0,x=1,y=56,width=668,height=324,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,varname="awardListView"
		},
		{
			name="ruleScrollView",type=0,typeName="ScrollView",time=0,x=0,y=10,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,varname="ruleScrollView"
		}
	}
}
return rank_rule_pop_layer;