--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		backButton = 1,
		ruleButton = 2,
		titleLightImage_1 = 3,
		titleLightImage_2 = 4,
		titleLightImage_3 = 5,
		radioButtonGroup = 6,
		gameRadiobutton = 7,
		profitRadiobutton = 8,
		moneyRadiobutton = 9,
		subTitleBg = 10,
		subRadioButtonGroup = 11,
		friendRankRadiobutton = 12,
		tabFriendLabel = 13,
		totalRankRadiobutton = 14,
		tabTotalLabel = 15,
		myRankView = 16,
		contentView = 17,
	},
	ui = {
		[1] = {"titleBg","backButton"},
		[2] = {"titleBg","ruleButton"},
		[3] = {"titleBg","titleView","titleLightImage_1"},
		[4] = {"titleBg","titleView","titleLightImage_2"},
		[5] = {"titleBg","titleView","titleLightImage_3"},
		[6] = {"titleBg","titleView","radioButtonGroup"},
		[7] = {"titleBg","titleView","radioButtonGroup","gameRadiobutton"},
		[8] = {"titleBg","titleView","radioButtonGroup","profitRadiobutton"},
		[9] = {"titleBg","titleView","radioButtonGroup","moneyRadiobutton"},
		[10] = {"subTitleBg"},
		[11] = {"subTitleBg","subRadioButtonGroup"},
		[12] = {"subTitleBg","subRadioButtonGroup","friendRankRadiobutton"},
		[13] = {"subTitleBg","subRadioButtonGroup","friendRankRadiobutton","tabFriendLabel"},
		[14] = {"subTitleBg","subRadioButtonGroup","totalRankRadiobutton"},
		[15] = {"subTitleBg","subRadioButtonGroup","totalRankRadiobutton","tabTotalLabel"},
		[16] = {"myRankView"},
		[17] = {"contentView"},
	},
	func = {
		[1] = "onBackButtonClick",
		[2] = "onRuleButtonClick",
	},
}
return MAP;