local hall_scene=
{
	name="hall_scene",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopRight,
	{
		name="hall_bg",type=1,typeName="Image",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="res/common/common_bg.png",varname="hall_bg"
	},
	{
		name="hall_girl",type=1,typeName="Image",time=0,x=-15,y=-10,width=382,height=580,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/hall/hall_girl.png",varname="hall_girl"
	},
	{
		name="playerInfo_node",type=0,typeName="View",time=0,x=14,y=10,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="playerInfo_node",
		{
			name="Image_head",type=1,typeName="Image",time=0,x=40,y=37,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/head/common_female_avatar.png",varname="Image_head"
		},
		{
			name="head_btn",type=1,typeName="Button",time=0,x=0,y=0,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_blank.png",varname="head_btn",callbackfunc="onHeadBtnClick"
		},
		{
			name="playerName",type=4,typeName="Text",time=0,x=90,y=15,width=200,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="playerName"
		},
		{
			name="gold_bg_btn",type=1,typeName="Button",time=0,x=82,y=47,width=173,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_chips_bg.png",varname="gold_bg_btn",callbackfunc="onAddBtnClick",
			{
				name="gold",type=1,typeName="Image",time=0,x=2,y=-1,width=31,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/common/common_gold_small.png",varname="gold"
			},
			{
				name="playerMoney",type=4,typeName="Text",time=0,x=34,y=0,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=200,colorBlue=0,string=[[222222222]],varname="playerMoney",colorA=1
			},
			{
				name="addGold_btn",type=1,typeName="Button",time=0,x=0,y=0,width=37,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/hall/hall_add_btn.png",varname="addGold_btn",callbackfunc="onAddBtnClick"
			}
		},
		{
			name="head_bg",type=1,typeName="Image",time=0,x=40,y=37,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_playerhead_bg.png",varname="head_bg"
		}
	},
	{
		name="View_vip",type=0,typeName="View",time=0,x=14,y=10,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="View_vip"
	},
	{
		name="ranking_node",type=1,typeName="Image",time=0,x=-3,y=13,width=305,height=482,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/hall/hall_ranking_bg.png",varname="ranking_node",
		{
			name="btn_bg",type=1,typeName="Image",time=0,x=0,y=20,width=234,height=53,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/hall/hall_changeTab_bg.png",varname="btn_bg",
			{
				name="rank_left_btn",type=1,typeName="Button",time=0,x=-55,y=0,width=117,height=53,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_blank.png",varname="rank_left_btn",callbackfunc="onRankingBtnClick",
				{
					name="left_bg",type=1,typeName="Image",time=0,x=0,y=0,width=117,height=45,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_changeTab_btn.png",varname="left_bg"
				},
				{
					name="left_text",type=4,typeName="Text",time=0,x=4,y=-4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Profit]],varname="left_text",colorA=1
				}
			},
			{
				name="rank_right_btn",type=1,typeName="Button",time=0,x=57,y=0,width=117,height=53,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_blank.png",varname="rank_right_btn",effect={shader="mirror",mirrorType=1},callbackfunc="onRankFriendsBtnClick",
				{
					name="right_bg",type=1,typeName="Image",time=0,x=0,y=0,width=117,height=45,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_changeTab_btn.png",varname="right_bg",effect={shader="mirror",mirrorType=1}
				},
				{
					name="right_text",type=4,typeName="Text",time=0,x=-1,y=-4,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Teman]],varname="right_text"
				}
			}
		},
		{
			name="ranking_list_view",type=0,typeName="ListView",time=0,x=0,y=73,width=252,height=385,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,varname="ranking_list_view"
		},
		{
			name="friends_list_view",type=0,typeName="ListView",time=0,x=0,y=73,width=252,height=385,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,varname="friends_list_view"
		},
		{
			name="noFriend_tips",type=0,typeName="View",time=0,x=0,y=73,width=252,height=385,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,varname="noFriend_tips",
			{
				name="NoFriendText",type=4,typeName="Text",time=0,x=0,y=-162,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=250,colorGreen=230,colorBlue=255,string=[[无好友]],colorA=1,varname="NoFriendText"
			},
			{
				name="Image86",type=1,typeName="Image",time=0,x=-100,y=-120,width=79,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/store/store_history_line.png"
			},
			{
				name="Image87",type=1,typeName="Image",time=0,x=100,y=-120,width=79,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/store/store_history_line.png"
			},
			{
				name="RecommendText",type=4,typeName="Text",time=0,x=0,y=-120,width=80,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=250,colorGreen=230,colorBlue=255,string=[[推荐好友]],colorA=1,varname="RecommendText"
			},
			{
				name="recommend_list_view",type=0,typeName="ListView",time=0,x=2,y=51,width=270,height=290,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="recommend_list_view"
			}
		},
		{
			name="LimitTimeEventBtn",type=1,typeName="Button",time=0,x=187,y=399,width=80,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/common/common_transparent.png",varname="LimitTimeEventBtn",callbackfunc="onLimitTimeEventBtnClick",
			{
				name="LimitTimeEventIcon",type=1,typeName="Image",time=0,x=2,y=-9,width=92,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/limitTimeEvent/lTEvent_time.png",varname="LimitTimeEventIcon"
			},
			{
				name="lTEvent_time_bg",type=1,typeName="Image",time=0,x=0,y=38,width=82,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/limitTimeEvent/lTEvent_time_hall_bg.png",varname="lTEvent_time_bg",
				{
					name="lTEvent_time",type=4,typeName="Text",time=0,x=0,y=0,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[00:00:00]],colorA=1,varname="lTEvent_time"
				}
			},
			{
				name="Image82",type=1,typeName="Image",time=0,x=0,y=20,width=84,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/limitTimeEvent/lTEvent_name.png"
			}
		},
		{
			name="LotteryBtn",type=1,typeName="Button",time=0,x=187,y=294,width=90,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/common/common_transparent.png",varname="LotteryBtn",callbackfunc="onLotteryClick",
			{
				name="Image91",type=1,typeName="Image",time=0,x=0,y=-4,width=76,height=76,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_lottery_btn.png"
			},
			{
				name="Image92",type=1,typeName="Image",time=0,x=0,y=24,width=68,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_lottery_word.png"
			},
			{
				name="LotteryNumBg",type=1,typeName="Image",time=0,x=56,y=10,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="LotteryNumBg",
				{
					name="LotteryNum",type=4,typeName="Text",time=0,x=-1,y=-1,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=102,string=[[0]],colorA=1,varname="LotteryNum"
				}
			}
		}
	},
	{
		name="bottomBtn_node",type=1,typeName="Image",time=0,x=0,y=0,width=960,height=73,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/hall/hall_bottomBtn_bg.png",varname="bottomBtn_node",
		{
			name="mall_btn",type=1,typeName="Button",time=0,x=61,y=-7,width=80,height=78,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common2_shop_btn.png",varname="mall_btn",callbackfunc="onMallBtnClick",
			{
				name="DiscountBg",type=1,typeName="Image",time=0,x=32,y=-29,width=54,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_store_sale.png",varname="DiscountBg",
				{
					name="DiscountLabel",type=4,typeName="Text",time=0,x=1,y=-6,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=51,string=[[Text]],colorA=1,varname="DiscountLabel"
				}
			}
		},
		{
			name="friend_btn",type=1,typeName="Button",time=0,x=173,y=10,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_friends_btn.png",varname="friend_btn",callbackfunc="onFriendsBtnClick",
			{
				name="msg_not_read_tips",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="msg_not_read_tips"
			}
		},
		{
			name="rank_btn",type=1,typeName="Button",time=0,x=288,y=10,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_rank_btn.png",varname="rank_btn",callbackfunc="onRankListBtnClick"
		},
		{
			name="task_btn",type=1,typeName="Button",time=0,x=407,y=10,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_task_btn.png",varname="task_btn",callbackfunc="onTaskBtnClick",
			{
				name="task_red_point",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="task_red_point"
			}
		},
		{
			name="activity_btn",type=1,typeName="Button",time=0,x=528,y=10,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_activity_btn.png",varname="activity_btn",callbackfunc="onActivityBtnClick",
			{
				name="redPointActivity",type=1,typeName="Image",time=0,x=54,y=6,width=24,height=26,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="redPointActivity"
			}
		},
		{
			name="freeMoney_btn",type=1,typeName="Button",time=0,x=640,y=10,width=108,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_freeChips_btn.png",varname="freeMoney_btn",callbackfunc="onFreeMoneyBtnClick",
			{
				name="Image_free_panel",type=1,typeName="Image",time=0,x=-115,y=-110,width=512,height=121,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_bt_di.png",gridLeft=35,gridRight=200,gridTop=35,gridBottom=35,varname="Image_free_panel",
				{
					name="Button_free_video",type=1,typeName="Button",time=0,x=403,y=12,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_video.png",varname="Button_free_video",callbackfunc="onFreeVideoBtnClick",
					{
						name="Text_free_video",type=4,typeName="Text",time=0,x=-6,y=52,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=239,colorGreen=210,colorBlue=254,string=[[Video]],colorA=1,varname="Text_free_video"
					},
					{
						name="Image_free_video_point",type=1,typeName="Image",time=0,x=59,y=1,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_video_point"
					}
				},
				{
					name="Button_free_download",type=1,typeName="Button",time=0,x=307,y=12,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_download.png",varname="Button_free_download",callbackfunc="onFreeDownloadBtnClick",
					{
						name="Text_free_download",type=4,typeName="Text",time=0,x=-4,y=52,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=239,colorGreen=210,colorBlue=254,string=[[Download]],colorA=1,varname="Text_free_download"
					},
					{
						name="Image_free_download_point",type=1,typeName="Image",time=0,x=57,y=1,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_download_point"
					}
				},
				{
					name="Button_free_login",type=1,typeName="Button",time=0,x=211,y=12,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_login.png",varname="Button_free_login",callbackfunc="onFreeLoginBtnClick",
					{
						name="Text_free_login",type=4,typeName="Text",time=0,x=-6,y=53,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=239,colorGreen=210,colorBlue=254,string=[[Text]],colorA=1,varname="Text_free_login"
					},
					{
						name="Image_free_login_point",type=1,typeName="Image",time=0,x=67,y=2,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_login_point"
					}
				},
				{
					name="Button_free_fans",type=1,typeName="Button",time=0,x=115,y=12,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_fans.png",varname="Button_free_fans",callbackfunc="onFreeFansBtnClick",
					{
						name="Text_free_fans",type=4,typeName="Text",time=0,x=-5,y=53,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=239,colorGreen=210,colorBlue=254,string=[[Text]],colorA=1,varname="Text_free_fans"
					},
					{
						name="Image_free_fans_point",type=1,typeName="Image",time=0,x=64,y=2,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_fans_point"
					}
				},
				{
					name="Button_free_upgrow",type=1,typeName="Button",time=0,x=19,y=12,width=89,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/freeGold/freeGold_upgrade.png",varname="Button_free_upgrow",callbackfunc="onFreeGrowBtnClick",
					{
						name="Text_free_upgrow",type=4,typeName="Text",time=0,x=-8,y=52,width=100,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=239,colorGreen=210,colorBlue=254,string=[[Text]],colorA=1,varname="Text_free_upgrow"
					},
					{
						name="Image_free_grow_point",type=1,typeName="Image",time=0,x=57,y=1,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_grow_point"
					}
				}
			},
			{
				name="Image_free_redPoint",type=1,typeName="Image",time=0,x=73,y=1,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_free_redPoint"
			}
		},
		{
			name="setting_btn",type=1,typeName="Button",time=0,x=840,y=21,width=64,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_setting_btn.png",varname="setting_btn",callbackfunc="onSettingBtnClick",
			{
				name="Image_setting_redPoint",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_setting_redPoint"
			}
		},
		{
			name="message_btn",type=1,typeName="Button",time=0,x=767,y=21,width=64,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_message_btn.png",varname="message_btn",callbackfunc="onMessageBtnClick",
			{
				name="red_point",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="red_point"
			}
		}
	},
	{
		name="quickStart_btn",type=1,typeName="Button",time=0,x=-1,y=-158,width=342,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/hall/hall_red_btn.png",varname="quickStart_btn",callbackfunc="onQuickStartBtnClick",
		{
			name="Image35",type=1,typeName="Image",time=0,x=10,y=4,width=87,height=76,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_gold_icon.png"
		},
		{
			name="Image36",type=1,typeName="Image",time=0,x=59,y=16,width=262,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_quickStart_txt.png"
		}
	},
	{
		name="gaple_btn",type=1,typeName="Button",time=0,x=-1,y=-43,width=342,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/hall/hall_yellow_btn.png",varname="gaple_btn",callbackfunc="onGapleBtnClick",
		{
			name="Image35",type=1,typeName="Image",time=0,x=17,y=-2,width=82,height=88,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_poker_icon.png"
		},
		{
			name="Image36",type=1,typeName="Image",time=0,x=114,y=4,width=138,height=88,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_gaple_icon.png"
		}
	},
	{
		name="qiuqiu_btn",type=1,typeName="Button",time=0,x=-1,y=65,width=342,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/hall/hall_blue_btn.png",varname="qiuqiu_btn",callbackfunc="onQiuqiuBtnClick",
		{
			name="Image35",type=1,typeName="Image",time=0,x=2,y=0,width=90,height=85,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_chips_icon.png"
		},
		{
			name="Image36",type=1,typeName="Image",time=0,x=117,y=8,width=150,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_qiuqiu_icon.png"
		},
		{
			name="room99_lock_icon",type=1,typeName="Image",time=0,x=250,y=20,width=64,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/roomChoose/roomC_clock_icon.png",varname="room99_lock_icon"
		}
	},
	{
		name="more_btn",type=1,typeName="Button",time=0,x=-1,y=173,width=342,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/hall/hall_purple_btn.png",varname="more_btn",callbackfunc="onMoreBtnClick",
		{
			name="Image35",type=1,typeName="Image",time=0,x=13,y=-6,width=75,height=96,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_dice_icon.png"
		},
		{
			name="Image36",type=1,typeName="Image",time=0,x=100,y=5,width=162,height=85,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/hall/hall_more_icon.png"
		},
		{
			name="roomC_clock_icon",type=1,typeName="Image",time=0,x=250,y=20,width=64,height=61,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/roomChoose/roomC_clock_icon.png",varname="roomC_clock_icon"
		}
	},
	{
		name="facebookButton",type=1,typeName="Button",time=0,x=1,y=9,width=94,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common2_invite_btn.png",varname="facebookButton",callbackfunc="onFacebookButtonClick",
		{
			name="fbLoginReward",type=4,typeName="Text",time=0,x=0,y=17,width=60,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignCenter,colorRed=255,colorGreen=240,colorBlue=0,string=[[+]],colorA=1,varname="fbLoginReward"
		},
		{
			name="inviteRed",type=1,typeName="Image",time=0,x=0,y=0,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="inviteRed"
		},
		{
			name="Image82",type=1,typeName="Image",time=0,x=0,y=41,width=54,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_invite_word.png"
		}
	},
	{
		name="firstPayBtn",type=1,typeName="Button",time=0,x=99,y=0,width=100,height=98,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_first_pay_light.png",varname="firstPayBtn",
		{
			name="Image83",type=1,typeName="Image",time=0,x=0,y=31,width=54,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_first_pay_word.png"
		},
		{
			name="Image87",type=1,typeName="Image",time=0,x=0,y=-5,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_first_pay.png"
		}
	},
	{
		name="LimitTimeBtn",type=1,typeName="Button",time=0,x=209,y=4,width=80,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_transparent.png",varname="LimitTimeBtn",callbackfunc="onLimitTimeClick",
		{
			name="Image83",type=1,typeName="Image",time=0,x=0,y=-10,width=56,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_limit_time_giftbag.png"
		},
		{
			name="Image82",type=1,typeName="Image",time=0,x=0,y=21,width=76,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_limit_time_giftbag_word.png"
		},
		{
			name="LimitTimeText",type=4,typeName="Text",time=0,x=0,y=37,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=102,string=[[Text]],colorA=1,varname="LimitTimeText"
		},
		{
			name="NumBg",type=1,typeName="Image",time=0,x=9,y=-31,width=54,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_store_sale.png",varname="NumBg",
			{
				name="NumText",type=4,typeName="Text",time=0,x=1,y=-6,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=153,string=[[99/99]],varname="NumText",colorA=1
			}
		}
	},
	{
		name="quickPayBtn",type=1,typeName="Button",time=0,x=111,y=18,width=76,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_quick_pay.png",varname="quickPayBtn"
	},
	{
		name="report_more_btn",type=1,typeName="Button",time=0,x=-1,y=173,width=342,height=108,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/common/common_blank.png",varname="report_more_btn",callbackfunc="onReportMoreBtnClick"
	}
}
return hall_scene;