require("view.view_config")
require("EngineCore.config")
require("utils.utilsInit")
require("config")
require("gameConfig")
require("game.updateInit")
require("language/languageInit")
require("EngineCoreex.coreexInit")
require("EngineCoreex.widgetBaseAnimEx")

