local fullService_event_layer=
{
	name="fullService_event_layer",type=0,typeName="View",time=0,x=0,y=0,width=680,height=400,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="Image15",type=1,typeName="Image",time=0,x=0,y=0,width=472,height=320,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/limitTimeEvent/lTEvent_right_content_bg.png",gridLeft=8,gridRight=1
	},
	{
		name="event_image_node",type=1,typeName="Image",time=0,x=12,y=17,width=190,height=170,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_frame_bg.png",varname="event_image_node",
		{
			name="event_icon",type=1,typeName="Image",time=0,x=0,y=0,width=220,height=118,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/default2.png",varname="event_icon"
		},
		{
			name="event_image",type=1,typeName="Image",time=0,x=0,y=0,width=190,height=170,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_transparent.png",varname="event_image"
		}
	},
	{
		name="rank_view",type=1,typeName="Image",time=0,x=12,y=200,width=190,height=191,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_rank_bg.png",gridLeft=15,gridRight=15,gridTop=40,gridBottom=20,varname="rank_view",
		{
			name="rank_scroller_view",type=0,typeName="ScrollView",time=0,x=0,y=33,width=180,height=156,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,varname="rank_scroller_view"
		},
		{
			name="rank_title",type=4,typeName="Text",time=0,x=0,y=7,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=16,textAlign=kAlignLeft,colorRed=220,colorGreen=190,colorBlue=255,varname="rank_title",colorA=1
		}
	},
	{
		name="countdown_time_bg",type=1,typeName="Image",time=0,x=323,y=16,width=250,height=32,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_time_bg.png",gridLeft=30,gridRight=30,gridTop=16,gridBottom=16,varname="countdown_time_bg",
		{
			name="fullService_event_time",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="fullService_event_time"
		}
	},
	{
		name="num_bar",type=1,typeName="Image",time=0,x=215,y=100,width=336,height=86,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_numBar_bg.png",varname="num_bar",
		{
			name="num_clip_view",type=0,typeName="View",time=0,x=0,y=0,width=100,height=76,visible=1,fillParentWidth=1,fillParentHeight=0,nodeAlign=kAlignCenter,varname="num_clip_view",
			{
				name="point_1",type=1,typeName="Image",time=0,x=193,y=22,width=34,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_num/lTEvent_node.png",varname="point_1"
			},
			{
				name="point_2",type=1,typeName="Image",time=0,x=71,y=22,width=34,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_num/lTEvent_node.png",varname="point_2"
			},
			{
				name="node_1",type=0,typeName="View",time=0,x=1,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_1",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_2",type=0,typeName="View",time=0,x=44,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_2",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_3",type=0,typeName="View",time=0,x=85,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_3",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_4",type=0,typeName="View",time=0,x=125,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_4",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_5",type=0,typeName="View",time=0,x=166,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_5",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_6",type=0,typeName="View",time=0,x=206,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_6",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_7",type=0,typeName="View",time=0,x=247,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_7",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			},
			{
				name="node_8",type=0,typeName="View",time=0,x=289,y=0,width=43,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="node_8",
				{
					name="point_21",type=1,typeName="Image",time=0,x=0,y=0,width=34,height=42,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/limitTimeEvent/lTEvent_num/lTEvent_9.png"
				}
			}
		},
		{
			name="Image43",type=1,typeName="Image",time=0,x=0,y=-61,width=44,height=18,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/limitTimeEvent/lTEvent_desc_left.png"
		},
		{
			name="Image44",type=1,typeName="Image",time=0,x=0,y=-61,width=44,height=18,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/limitTimeEvent/lTEvent_desc_right.png"
		}
	},
	{
		name="fullService_event_name",type=4,typeName="Text",time=0,x=45,y=-120,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,colorA=1,varname="fullService_event_name",string=[[text]]
	},
	{
		name="Image41",type=1,typeName="Image",time=0,x=217,y=101,width=333,height=84,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_numBar_shader.png"
	},
	{
		name="getRewardBtn",type=1,typeName="Button",time=0,x=575,y=75,width=86,height=86,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_transparent.png",varname="getRewardBtn",callbackfunc="onGetRewardBtnClick",
		{
			name="reward_view",type=1,typeName="Image",time=0,x=0,y=0,width=86,height=86,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_reward_bg.png",varname="reward_view",
			{
				name="Image24",type=1,typeName="Image",time=0,x=0,y=0,width=106,height=104,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/limitTimeEvent/lTEvent_star.png"
			},
			{
				name="reward_icon",type=1,typeName="Image",time=0,x=-4,y=0,width=93,height=67,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_coin_101.png",varname="reward_icon"
			}
		},
		{
			name="Image25",type=1,typeName="Image",time=0,x=2,y=66,width=82,height=20,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/limitTimeEvent/lTEvent_time_hall_bg.png",
			{
				name="reward_text",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignCenter,colorRed=255,colorGreen=215,colorBlue=0,string=[[Text]],colorA=1,varname="reward_text"
			}
		},
		{
			name="reward_condition",type=4,typeName="Text",time=0,x=0,y=60,width=48,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=20,textAlign=kAlignCenter,colorRed=220,colorGreen=190,colorBlue=255,colorA=1,varname="reward_condition"
		}
	},
	{
		name="hasGetReward",type=1,typeName="Image",time=0,x=278,y=-82,width=52,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/limitTimeEvent/lTEvent_reward_geted.png",varname="hasGetReward"
	},
	{
		name="fullService_event_desc",type=0,typeName="ScrollView",time=0,x=225,y=200,width=441,height=130,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="fullService_event_desc"
	},
	{
		name="quick_play_btn",type=1,typeName="Button",time=0,x=100,y=162,width=232,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_btn_yellow.png",gridLeft=50,gridRight=50,gridTop=35,gridBottom=34,varname="quick_play_btn",callbackfunc="onQuickPlayBtnClick",
		{
			name="quick_play_taxt",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="quick_play_taxt",colorA=1
		}
	}
}
return fullService_event_layer;