local roomGaple_scene=
{
	name="roomGaple_scene",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTop,
	{
		name="centerNode",type=0,typeName="View",time=0,x=0,y=-60,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="centerNode"
	},
	{
		name="backgroundNode",type=1,typeName="Image",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="res/room/gaple/roomG_bg.png",varname="backgroundNode",callbackfunc="onBackgroundTouch",
		{
			name="topInfoBg",type=1,typeName="Image",time=0,x=0,y=0,width=384,height=70,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/roomG_top_light.png",varname="topInfoBg",
			{
				name="Image7",type=1,typeName="Image",time=0,x=75,y=5,width=33,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_gold_big.png",
				{
					name="chip_node",type=0,typeName="View",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="chip_node"
				}
			},
			{
				name="prizePool",type=4,typeName="Text",time=0,x=110,y=6,width=220,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=200,colorBlue=75,string=[[8,888,888,888,888]],colorA=1,varname="prizePool"
			}
		},
		{
			name="roomInfo",type=4,typeName="Text",time=0,x=0,y=80,width=100,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=20,textAlign=kAlignCenter,colorRed=200,colorGreen=160,colorBlue=255,string=[[roomInfo]],colorA=1,varname="roomInfo"
		},
		{
			name="privateRoomInfo",type=4,typeName="Text",time=0,x=0,y=120,width=100,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=20,textAlign=kAlignCenter,colorRed=69,colorGreen=38,colorBlue=93,string=[[privateRoomInfo]],colorA=1,varname="privateRoomInfo"
		},
		{
			name="countDownTipsBg",type=1,typeName="Image",time=0,x=0,y=-20,width=542,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/room/gaple/roomG_round_pass_bg.png",varname="countDownTipsBg",
			{
				name="countDownTipsText",type=4,typeName="Text",time=0,x=0,y=0,width=500,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=233,colorGreen=255,colorBlue=80,string=[[下一局时间]],colorA=1,varname="countDownTipsText"
			}
		},
		{
			name="ruleTipsBg",type=1,typeName="Image",time=0,x=0,y=95,width=538,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/room/gaple/roomG_rule_tips.png",varname="ruleTipsBg",
			{
				name="ruleTipsClip",type=1,typeName="Image",time=0,x=0,y=0,width=518,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_blank.png",varname="ruleTipsClip",
				{
					name="ruleTipsText",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=20,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="ruleTipsText"
				}
			}
		},
		{
			name="waitBg",type=1,typeName="Image",time=0,x=0,y=75,width=542,height=48,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/room/gaple/roomG_round_pass_bg.png",varname="waitBg",
			{
				name="waitText",type=4,typeName="Text",time=0,x=0,y=0,width=500,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=26,textAlign=kAlignCenter,colorRed=233,colorGreen=255,colorBlue=80,colorA=1,varname="waitText"
			}
		}
	},
	{
		name="dealerNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="dealerNode",
		{
			name="clock",type=4,typeName="Text",time=0,x=20,y=85,width=50,height=16,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=14,textAlign=kAlignCenter,colorRed=240,colorGreen=208,colorBlue=255,string=[[12:12]],colorA=1,varname="clock"
		},
		{
			name="signal",type=0,typeName="View",time=0,x=28,y=109,width=30,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="signal",
			{
				name="signal4",type=1,typeName="Image",time=0,x=0,y=4,width=27,height=8,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/roomG_signal_4.png",varname="signal4"
			},
			{
				name="signal3",type=1,typeName="Image",time=0,x=0,y=8,width=19,height=8,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/roomG_signal_3.png",varname="signal3"
			},
			{
				name="signal2",type=1,typeName="Image",time=0,x=0,y=14,width=13,height=6,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/roomG_signal_2.png",varname="signal2"
			},
			{
				name="signal1",type=1,typeName="Image",time=0,x=0,y=20,width=5,height=4,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/roomG_signal_1.png",varname="signal1"
			},
			{
				name="signalNo",type=1,typeName="Image",time=0,x=0,y=-2,width=29,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/room/gaple/roomG_signal_no.png",varname="signalNo"
			}
		},
		{
			name="dealerIcon",type=1,typeName="Image",time=0,x=465,y=207,width=27,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/room/gaple/roomG_table_dealer_icon.png",varname="dealerIcon"
		},
		{
			name="dealerIcon__",type=1,typeName="Image",time=0,x=0,y=-100,width=27,height=27,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/room/gaple/roomG_table_dealer_icon.png",varname="dealerIcon__"
		}
	},
	{
		name="chipNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="chipNode"
	},
	{
		name="seatNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="seatNode"
	},
	{
		name="dealCardNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="dealCardNode"
	},
	{
		name="lampNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="lampNode",
		{
			name="lampNod",type=0,typeName="View",time=0,x=0,y=-58,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="lampNod",
			{
				name="lampImage",type=1,typeName="Image",time=0,x=0,y=0,width=70,height=350,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/room/gaple/room_table_light.png",varname="lampImage"
			}
		}
	},
	{
		name="oprNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="oprNode",
		{
			name="chatBtn",type=1,typeName="Button",time=0,x=10,y=10,width=70,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="res/room/gaple/roomG_talk_btn.png",varname="chatBtn",callbackfunc="onChatBtnClick"
		},
		{
			name="chatMsgNoRead",type=1,typeName="Image",time=0,x=4,y=53,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="chatMsgNoRead"
		}
	},
	{
		name="animNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="animNode"
	},
	{
		name="topNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="topNode",
		{
			name="menuBtn",type=1,typeName="Button",time=0,x=10,y=10,width=70,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/room/gaple/roomG_more_btn.png",varname="menuBtn",callbackfunc="onMenuBtnClick"
		},
		{
			name="menuBg",type=1,typeName="Image",time=0,x=415,y=440,width=-1,height=-1,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,file="res/common/common_transparent_blank.png",varname="menuBg",
			{
				name="menuBg_",type=1,typeName="Image",time=0,x=-4,y=60,width=275,height=318,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/room/gaple/roomG_more_bg.png",
				{
					name="lobbyBtn",type=1,typeName="Button",time=0,x=0,y=26,width=230,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_blank.png",varname="lobbyBtn",callbackfunc="onReturnBtnClick",
					{
						name="Image29",type=1,typeName="Image",time=0,x=15,y=0,width=58,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/room/gaple/roomG_return_btn.png"
					},
					{
						name="Text30",type=4,typeName="Text",time=0,x=80,y=0,width=140,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Lobby]],colorA=1
					}
				},
				{
					name="changeRoomBtn",type=1,typeName="Button",time=0,x=0,y=93,width=230,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_blank.png",varname="changeRoomBtn",callbackfunc="onChangeRoomBtnClick",
					{
						name="Image29",type=1,typeName="Image",time=0,x=15,y=0,width=58,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/room/gaple/roomG_change_btn.png"
					},
					{
						name="Text30",type=4,typeName="Text",time=0,x=80,y=0,width=140,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Pindah]],colorA=1
					}
				},
				{
					name="standUpBtn",type=1,typeName="Button",time=0,x=0,y=162,width=230,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_blank.png",varname="standUpBtn",callbackfunc="onStandUpBtnClick",
					{
						name="Image29",type=1,typeName="Image",time=0,x=15,y=0,width=58,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/room/gaple/roomG_standUp_btn.png"
					},
					{
						name="Text30",type=4,typeName="Text",time=0,x=80,y=0,width=140,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Bangun]],colorA=1
					}
				},
				{
					name="settingBtn",type=1,typeName="Button",time=0,x=0,y=230,width=230,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_blank.png",varname="settingBtn",callbackfunc="onSettingBtnClick",
					{
						name="Image29",type=1,typeName="Image",time=0,x=15,y=0,width=58,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/room/gaple/roomG_setting_btn.png"
					},
					{
						name="Text30",type=4,typeName="Text",time=0,x=80,y=0,width=140,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Pengaturan]],colorA=1
					}
				}
			}
		}
	},
	{
		name="inviteBtn",type=1,typeName="Button",time=0,x=10,y=10,width=70,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/room/gaple/roomG__invite_btn.png",varname="inviteBtn",callbackfunc="onInviteBtnClick",
		{
			name="fbLoginReward",type=4,typeName="Text",time=0,x=0,y=12,width=1,height=1,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=15,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=102,string=[[+2M]],colorA=1,varname="fbLoginReward"
		}
	},
	{
		name="mallBtn",type=1,typeName="Button",time=0,x=100,y=10,width=70,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/room/gaple/roomG__shop_btn.png",varname="mallBtn",callbackfunc="onMallBtnClick",
		{
			name="DiscountBg",type=1,typeName="Image",time=0,x=38,y=-5,width=43,height=25,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common2_store_sale.png",varname="DiscountBg",
			{
				name="DiscountText",type=4,typeName="Text",time=0,x=1,y=-6,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=51,string=[[Text]],colorA=1,varname="DiscountText"
			}
		}
	},
	{
		name="popupNode",type=0,typeName="View",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,varname="popupNode"
	},
	{
		name="firstPayBtn",type=1,typeName="Button",time=0,x=190,y=7,width=70,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_transparent.png",varname="firstPayBtn",
		{
			name="Image69",type=1,typeName="Image",time=0,x=0,y=0,width=100,height=98,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_first_pay_light.png"
		},
		{
			name="Image66",type=1,typeName="Image",time=0,x=0,y=0,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_first_pay.png"
		},
		{
			name="Image67",type=1,typeName="Image",time=0,x=0,y=24,width=64,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_first_pay_word.png"
		}
	},
	{
		name="quickPayBtn",type=1,typeName="Button",time=0,x=187,y=14,width=76,height=56,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_quick_pay.png",varname="quickPayBtn"
	},
	{
		name="LimitTimeGift",type=1,typeName="Button",time=0,x=90,y=8,width=74,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_transparent.png",varname="LimitTimeGift",callbackfunc="onLimitTimeClick",
		{
			name="Image69",type=1,typeName="Image",time=0,x=0,y=-10,width=56,height=54,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_limit_time_giftbag.png"
		},
		{
			name="Image67",type=1,typeName="Image",time=0,x=0,y=21,width=76,height=22,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common2_limit_time_giftbag_word.png"
		},
		{
			name="LimitTimeText",type=4,typeName="Text",time=0,x=0,y=37,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=18,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=102,string=[[Text]],colorA=1,varname="LimitTimeText"
		},
		{
			name="NumBg",type=1,typeName="Image",time=0,x=38,y=-5,width=43,height=25,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common2_store_sale.png",varname="NumBg",
			{
				name="NumText",type=4,typeName="Text",time=0,x=1,y=-6,width=1,height=1,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=16,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=102,string=[[Text]],colorA=1,varname="NumText"
			}
		}
	}
}
return roomGaple_scene;