local friend_item_layer=
{
	name="friend_item_layer",type=0,typeName="View",time=0,x=0,y=0,width=860,height=99,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,
	{
		name="bg",type=1,typeName="Image",time=0,x=0,y=0,width=856,height=99,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/friend/friend_item_bg.png",
		{
			name="headButton",type=1,typeName="Button",time=0,x=20,y=0,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/common/common_transparent.png",varname="headButton",callbackfunc="onHeadButtonClick",
			{
				name="headImage",type=1,typeName="Image",time=0,x=0,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_nophoto.jpg",varname="headImage"
			},
			{
				name="Vipk",type=1,typeName="Image",time=0,x=0,y=0,width=80,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/hall/hall_playerhead_bg.png",varname="Vipk"
			}
		},
		{
			name="View_vip",type=0,typeName="View",time=0,x=20,y=8,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="View_vip"
		},
		{
			name="nameLabel",type=4,typeName="Text",time=0,x=174,y=20,width=286,height=24,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Domin]],varname="nameLabel",colorA=1
		},
		{
			name="Image7",type=1,typeName="Image",time=0,x=133,y=54,width=31,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_gold_small.png"
		},
		{
			name="moneyLabel",type=4,typeName="Text",time=0,x=174,y=57,width=244,height=23,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignLeft,colorRed=255,colorGreen=246,colorBlue=0,string=[[0]],colorA=1,varname="moneyLabel"
		},
		{
			name="statusLabel",type=4,typeName="Text",time=0,x=126,y=0,width=192,height=41,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=22,textAlign=kAlignCenter,colorRed=160,colorGreen=160,colorBlue=160,string=[[Off-line]],colorA=1,varname="statusLabel"
		},
		{
			name="sendMoneyButton",type=1,typeName="Button",time=0,x=653,y=8,width=72,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/friend/friend_send_money.png",varname="sendMoneyButton",callbackfunc="onSendMoneyButtonClick",
			{
				name="sendMoneyLabel",type=4,typeName="Text",time=0,x=6,y=-56,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=14,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[赠送金币]],colorA=1,varname="sendMoneyLabel"
			}
		},
		{
			name="chatButton",type=1,typeName="Button",time=0,x=751,y=8,width=72,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/friend/friend_message.png",varname="chatButton",callbackfunc="onChatButtonClick",
			{
				name="chatLabel",type=4,typeName="Text",time=0,x=6,y=-56,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,fontSize=14,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[聊天]],colorA=1,varname="chatLabel"
			}
		},
		{
			name="addButton",type=1,typeName="Button",time=0,x=19,y=0,width=192,height=69,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/common/common_btn_yellow.png",gridLeft=50,gridRight=50,gridTop=35,gridBottom=34,varname="addButton",callbackfunc="onAddButtonClick",
			{
				name="addLabel",type=4,typeName="Text",time=0,x=0,y=0,width=100,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[添加]],colorA=1,varname="addLabel"
			}
		},
		{
			name="new_chat_point",type=1,typeName="Image",time=0,x=796,y=11,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="new_chat_point"
		},
		{
			name="SexIcon",type=1,typeName="Image",time=0,x=135,y=19,width=30,height=30,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_sex_woman_icon.png",varname="SexIcon"
		}
	}
}
return friend_item_layer;