--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		middleBtn_bg = 1,
		all_btn = 2,
		all_btn_bg = 3,
		all_btn_text = 4,
		self_buy_btn = 5,
		self_buy_bg = 6,
		self_buy_text = 7,
		friends_send_btn = 8,
		friend_send_bg = 9,
		friend_send_text = 10,
		system_send_btn = 11,
		system_send_bg = 12,
		system_send_text = 13,
		gift_scroll_view = 14,
		noGift_tips = 15,
		tips = 16,
	},
	ui = {
		[1] = {"middleBtn_bg"},
		[2] = {"middleBtn_bg","all_btn"},
		[3] = {"middleBtn_bg","all_btn","all_btn_bg"},
		[4] = {"middleBtn_bg","all_btn","all_btn_text"},
		[5] = {"middleBtn_bg","self_buy_btn"},
		[6] = {"middleBtn_bg","self_buy_btn","self_buy_bg"},
		[7] = {"middleBtn_bg","self_buy_btn","self_buy_text"},
		[8] = {"middleBtn_bg","friends_send_btn"},
		[9] = {"middleBtn_bg","friends_send_btn","friend_send_bg"},
		[10] = {"middleBtn_bg","friends_send_btn","friend_send_text"},
		[11] = {"middleBtn_bg","system_send_btn"},
		[12] = {"middleBtn_bg","system_send_btn","system_send_bg"},
		[13] = {"middleBtn_bg","system_send_btn","system_send_text"},
		[14] = {"gift_scroll_view"},
		[15] = {"noGift_tips"},
		[16] = {"tips"},
	},
	func = {
		[2] = "onAllBtnClick",
		[5] = "onSelfBuyBtnClick",
		[8] = "onFriendsSendBtnClick",
		[11] = "onSystemSendBtnClick",
	},
}
return MAP;