--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		Image_bg = 1,
		titleTxt = 2,
		nameTitleTxt = 3,
		Image_edit = 4,
		EditText_name_ = 5,
		sexTitleTxt = 6,
		sexSelect = 7,
		CheckBoxGroup_sex = 8,
		womanTxt = 9,
		manTxt = 10,
		headTitleTxt = 11,
		changeHeadBtn = 12,
		changeHeadTxt = 13,
		signTitleTxt = 14,
		EditText_sign = 15,
		fbTitleTxt = 16,
		Button_effect37 = 17,
		Button10 = 18,
		btnTxt = 19,
	},
	ui = {
		[1] = {"Image_bg"},
		[2] = {"Image_bg","titleTxt"},
		[3] = {"Image_bg","nameTitleTxt"},
		[4] = {"Image_bg","nameTitleTxt","Image_edit"},
		[5] = {"Image_bg","nameTitleTxt","EditText_name_"},
		[6] = {"Image_bg","sexTitleTxt"},
		[7] = {"Image_bg","sexTitleTxt","sexSelect"},
		[8] = {"Image_bg","sexTitleTxt","sexSelect","CheckBoxGroup_sex"},
		[9] = {"Image_bg","sexTitleTxt","sexSelect","womanTxt"},
		[10] = {"Image_bg","sexTitleTxt","sexSelect","manTxt"},
		[11] = {"Image_bg","headTitleTxt"},
		[12] = {"Image_bg","headTitleTxt","changeHeadBtn"},
		[13] = {"Image_bg","headTitleTxt","changeHeadBtn","changeHeadTxt"},
		[14] = {"Image_bg","signTitleTxt"},
		[15] = {"Image_bg","signTitleTxt","EditText_sign"},
		[16] = {"Image_bg","fbTitleTxt"},
		[17] = {"Image_bg","fbTitleTxt","Button_effect37"},
		[18] = {"Image_bg","Button10"},
		[19] = {"Image_bg","Button10","btnTxt"},
	},
	func = {
		[1] = "onPopupBgTouch",
		[4] = "onEditBtnHandler",
		[18] = "confirmInfo",
	},
}
return MAP;