--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		Image_bg = 1,
		Button_close = 2,
		View_basic_info = 3,
		Text_person_uid = 4,
		Text_person_lv = 5,
		Text_person_money = 6,
		Text_person_charm = 7,
		Button_userIcon = 8,
		Image_user_icon = 9,
		View_vip = 10,
		Button_gift_big = 11,
		Image_gift_icon = 12,
		Button_edit_user_profile = 13,
		Text_edit_user_profile_key = 14,
		Image_sex_icon = 15,
		Image_lv_icon = 16,
		Image_ThumbIcon = 17,
		Text_person_name = 18,
		View_album = 19,
		Button_thumbup = 20,
		Button_camera = 21,
		Image_subview = 22,
		Image_tab = 23,
		View_toolbar = 24,
		View_hd_prop_plugin = 25,
	},
	ui = {
		[1] = {"Image_bg"},
		[2] = {"Image_bg","Button_close"},
		[3] = {"Image_bg","View_basic_info"},
		[4] = {"Image_bg","View_basic_info","Text_person_uid"},
		[5] = {"Image_bg","View_basic_info","Text_person_lv"},
		[6] = {"Image_bg","View_basic_info","Text_person_money"},
		[7] = {"Image_bg","View_basic_info","Text_person_charm"},
		[8] = {"Image_bg","View_basic_info","Button_userIcon"},
		[9] = {"Image_bg","View_basic_info","Button_userIcon","View61","Image_user_icon"},
		[10] = {"Image_bg","View_basic_info","View_vip"},
		[11] = {"Image_bg","View_basic_info","Button_gift_big"},
		[12] = {"Image_bg","View_basic_info","Button_gift_big","Image_gift_icon"},
		[13] = {"Image_bg","View_basic_info","Button32"},
		[14] = {"Image_bg","View_basic_info","Button32","Text33"},
		[15] = {"Image_bg","View_basic_info","Image42"},
		[16] = {"Image_bg","View_basic_info","Image52"},
		[17] = {"Image_bg","View_basic_info","Image53"},
		[18] = {"Image_bg","View_basic_info","TextView54"},
		[19] = {"Image_bg","View_album"},
		[20] = {"Image_bg","View_album","Button_thumbup"},
		[21] = {"Image_bg","View_album","Button_camera"},
		[22] = {"Image_bg","Image_subview"},
		[23] = {"Image_bg","Image_tab"},
		[24] = {"Image_bg","View_toolbar"},
		[25] = {"Image_bg","View31"},
	},
	func = {
		[1] = "onPopupBgTouch",
		[2] = "onBgTouch",
		[8] = "onBtnUserIconClick",
		[11] = "onBtnGiftClick",
		[13] = "onBtnEditUserProfileClick",
		[20] = "onBtnThumbUpClick",
		[21] = "onBtnCameraClick",
	},
}
return MAP;