local store_indomogPay_pop_layer=
{
	name="store_indomogPay_pop_layer",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="Image_touch",type=1,typeName="Image",time=0,x=0,y=0,width=-1,height=-1,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="res/common/common_blank.png",varname="Image_touch",callbackfunc="onCloseButtonClick"
	},
	{
		name="bg",type=1,typeName="Image",time=0,x=0,y=0,width=725,height=430,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_popup_bg_small.png",varname="bg",callbackfunc="itemTouch",
		{
			name="Image3",type=1,typeName="Image",time=0,x=0,y=12,width=480,height=77,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,file="res/common/common_pop_bg_title.png",gridLeft=150,gridRight=150,gridTop=35,gridBottom=35,
			{
				name="titleLabel",type=4,typeName="Text",time=0,x=0,y=0,width=325,height=74,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,varname="titleLabel",colorA=1
			}
		},
		{
			name="closeButton",type=1,typeName="Button",time=0,x=20,y=22,width=51,height=52,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_pop_close.png",varname="closeButton",callbackfunc="onCloseButtonClick"
		},
		{
			name="accountLabel",type=4,typeName="Text",time=0,x=103,y=139,width=100,height=51,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,varname="accountLabel",colorA=1
		},
		{
			name="passwordLabel",type=4,typeName="Text",time=0,x=103,y=209,width=100,height=51,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,varname="passwordLabel"
		},
		{
			name="accountEditBoxBg",type=1,typeName="Image",time=0,x=246,y=136,width=354,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_password_bg.png",gridLeft=15,gridRight=15,gridTop=15,gridBottom=15,
			{
				name="accountEditBox",type=6,typeName="EditText",time=0,x=7,y=4,width=337,height=49,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,colorA=1,varname="accountEditBox"
			}
		},
		{
			name="passwordEditBoxBg",type=1,typeName="Image",time=0,x=246,y=206,width=354,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_password_bg.png",gridLeft=15,gridRight=15,gridTop=15,gridBottom=15,
			{
				name="passwordEditBox",type=6,typeName="EditText",time=0,x=7,y=4,width=337,height=49,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,colorA=1,varname="passwordEditBox"
			}
		},
		{
			name="View12",type=0,typeName="View",time=0,x=0,y=50,width=450,height=100,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,
			{
				name="sureButton",type=1,typeName="Button",time=0,x=0,y=0,width=192,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/common/common_btn_yellow.png",gridLeft=50,gridRight=50,gridTop=35,gridBottom=34,varname="sureButton",callbackfunc="onSureButtonClick",
				{
					name="sureLabel",type=4,typeName="Text",time=0,x=0,y=0,width=130,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,varname="sureLabel"
				}
			},
			{
				name="cancelButton",type=1,typeName="Button",time=0,x=0,y=0,width=192,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="res/common/common_btn_purple.png",varname="cancelButton",callbackfunc="onCancelButtonClick",
				{
					name="cancelLabel",type=4,typeName="Text",time=0,x=0,y=0,width=130,height=42,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,varname="cancelLabel"
				}
			}
		}
	}
}
return store_indomogPay_pop_layer;