--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		Bg = 1,
		ContentView = 2,
		Time = 3,
		Text1 = 4,
		Text2 = 5,
		Gift4 = 6,
		GiftName4 = 7,
		Gift2 = 8,
		GiftName2 = 9,
		Gift1 = 10,
		GiftName1 = 11,
		Gift3 = 12,
		GiftName3 = 13,
		ChangeBtn = 14,
		PayIcon = 15,
		BuyButton = 16,
		BuyText = 17,
		Image_discount = 18,
		Text_discount = 19,
		Text3 = 20,
		PayMore = 21,
		PayListView = 22,
	},
	ui = {
		[1] = {"Bg"},
		[2] = {"Bg","ContentView"},
		[3] = {"Bg","ContentView","Image33","Time"},
		[4] = {"Bg","ContentView","Text1"},
		[5] = {"Bg","ContentView","Text2"},
		[6] = {"Bg","ContentView","Image34","Image36","Gift4"},
		[7] = {"Bg","ContentView","Image34","Image36","GiftName4"},
		[8] = {"Bg","ContentView","Image34","Image27","Gift2"},
		[9] = {"Bg","ContentView","Image34","Image27","GiftName2"},
		[10] = {"Bg","ContentView","Image34","Image11","Gift1"},
		[11] = {"Bg","ContentView","Image34","Image11","GiftName1"},
		[12] = {"Bg","ContentView","Image34","Image30","Gift3"},
		[13] = {"Bg","ContentView","Image34","Image30","GiftName3"},
		[14] = {"Bg","ContentView","Image10","ChangeBtn"},
		[15] = {"Bg","ContentView","Image10","PayIcon"},
		[16] = {"Bg","ContentView","BuyButton"},
		[17] = {"Bg","ContentView","BuyButton","BuyText"},
		[18] = {"Bg","ContentView","Image_discount"},
		[19] = {"Bg","ContentView","Image_discount","Text_discount"},
		[20] = {"Bg","ContentView","Text3"},
		[21] = {"Bg","PayMore"},
		[22] = {"Bg","PayMore","PayListView"},
	},
	func = {
		[1] = "onPopupBgTouch",
		[14] = "onPayChangeClick",
		[16] = "onBuy",
	},
}
return MAP;