--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		Image_bg = 1,
		Text_title = 2,
		Image_item1 = 3,
		Text_tip = 4,
		Text_info = 5,
		Button_get = 6,
		Text_bt_get = 7,
		Image_item2 = 8,
		Text_tip2 = 9,
		Text_info2 = 10,
		Button_get2 = 11,
		Text_bt_get2 = 12,
		Image_item3 = 13,
		Text_tip3 = 14,
		Text_info3 = 15,
		Button_get3 = 16,
		Text_bt_get3 = 17,
		Img_bonus = 18,
		Img_discount = 19,
		discount = 20,
	},
	ui = {
		[1] = {"Image_bg"},
		[2] = {"Image_bg","Image11","Text_title"},
		[3] = {"Image_bg","Image_item1"},
		[4] = {"Image_bg","Image_item1","Text_tip"},
		[5] = {"Image_bg","Image_item1","Text_info"},
		[6] = {"Image_bg","Image_item1","Button_get"},
		[7] = {"Image_bg","Image_item1","Button_get","Text_bt_get"},
		[8] = {"Image_bg","Image_item2"},
		[9] = {"Image_bg","Image_item2","Text_tip2"},
		[10] = {"Image_bg","Image_item2","Text_info2"},
		[11] = {"Image_bg","Image_item2","Button_get2"},
		[12] = {"Image_bg","Image_item2","Button_get2","Text_bt_get2"},
		[13] = {"Image_bg","Image_item3"},
		[14] = {"Image_bg","Image_item3","Text_tip3"},
		[15] = {"Image_bg","Image_item3","Text_info3"},
		[16] = {"Image_bg","Image_item3","Button_get3"},
		[17] = {"Image_bg","Image_item3","Button_get3","Text_bt_get3"},
		[18] = {"Image_bg","Image_item3","Button_get3","Img_bonus"},
		[19] = {"Image_bg","Image_item3","Button_get3","Img_discount"},
		[20] = {"Image_bg","Image_item3","Button_get3","Img_discount","discount"},
	},
	func = {
		[1] = "onPopupBgTouch",
		[6] = "bt_get_click",
		[11] = "bt_get_click2",
		[16] = "bt_get_click3",
	},
}
return MAP;