--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		login_bg = 1,
		login_girl = 2,
		login_logo_node = 3,
		login_logo = 4,
		login_FB = 5,
		login_guest = 6,
		guest_tips = 7,
		login_single = 8,
		login_copyright = 9,
		debug_view = 10,
		offline_btn = 11,
		offline_text = 12,
		onLine_btn = 13,
		onLine_text = 14,
		china_btn = 15,
		china_text = 16,
		yinni_btn = 17,
		yinni_text = 18,
		change_btn = 19,
		check_url = 20,
	},
	ui = {
		[1] = {"login_bg"},
		[2] = {"login_girl"},
		[3] = {"login_logo_node"},
		[4] = {"login_logo_node","login_logo"},
		[5] = {"login_FB"},
		[6] = {"login_guest"},
		[7] = {"login_guest","guest_tips"},
		[8] = {"login_single"},
		[9] = {"login_copyright"},
		[10] = {"debug_view"},
		[11] = {"debug_view","offline_btn"},
		[12] = {"debug_view","offline_btn","offline_text"},
		[13] = {"debug_view","onLine_btn"},
		[14] = {"debug_view","onLine_btn","onLine_text"},
		[15] = {"debug_view","china_btn"},
		[16] = {"debug_view","china_btn","china_text"},
		[17] = {"debug_view","yinni_btn"},
		[18] = {"debug_view","yinni_btn","yinni_text"},
		[19] = {"debug_view","change_btn"},
		[20] = {"debug_view","check_url"},
	},
	func = {
		[5] = "onloginFBBtnClick",
		[6] = "onLoginGuestBtnClick",
		[8] = "onLoginSingleBtnClick",
		[11] = "onOffLineBtnClick",
		[13] = "onOnLineBtnClick",
		[15] = "onChinaBtnClick",
		[17] = "onYinniBtnClick",
		[19] = "onChangeBtnClick",
	},
}
return MAP;