local login_scene=
{
	name="login_scene",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,
	{
		name="login_bg",type=1,typeName="Image",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="res/common/common_bg.png",varname="login_bg"
	},
	{
		name="login_girl",type=1,typeName="Image",time=0,x=-196,y=0,width=502,height=640,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottom,file="res/common/common_girl.png",varname="login_girl"
	},
	{
		name="login_logo_node",type=0,typeName="View",time=0,x=96,y=-35,width=284,height=208,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,varname="login_logo_node",
		{
			name="login_logo",type=1,typeName="Image",time=0,x=0,y=0,width=262,height=138,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_logo.png",varname="login_logo"
		}
	},
	{
		name="login_FB",type=1,typeName="Button",time=0,x=35,y=8,width=409,height=142,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/login/login_fb_btn.png",varname="login_FB",callbackfunc="onloginFBBtnClick",
		{
			name="Image11",type=1,typeName="Image",time=0,x=25,y=70,width=360,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/login/login_fb_desc.png"
		}
	},
	{
		name="login_guest",type=1,typeName="Button",time=0,x=35,y=163,width=409,height=142,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/login/login_guest__btn.png",varname="login_guest",callbackfunc="onLoginGuestBtnClick",
		{
			name="guest_tips",type=5,typeName="TextView",time=0,x=0,y=130,width=450,height=60,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=22,textAlign=kAlignTop,colorRed=255,colorGreen=255,colorBlue=255,string=[[tips]],colorA=1,varname="guest_tips"
		}
	},
	{
		name="login_single",type=1,typeName="Button",time=0,x=95,y=208,width=301,height=73,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/login/login_single_btn.png",varname="login_single",callbackfunc="onLoginSingleBtnClick"
	},
	{
		name="login_copyright",type=4,typeName="Text",time=0,x=30,y=10,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignBottomRight,fontSize=14,textAlign=kAlignLeft,colorRed=111,colorGreen=70,colorBlue=151,string=[[Copyright © 2015 Boyaa Interactive International Limited.common_log.V]],colorA=1,varname="login_copyright"
	},
	{
		name="debug_view",type=0,typeName="View",time=0,x=200,y=30,width=378,height=100,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,varname="debug_view",
		{
			name="offline_btn",type=1,typeName="Button",time=0,x=0,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/button.png",varname="offline_btn",callbackfunc="onOffLineBtnClick",
			{
				name="offline_text",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[测试]],colorA=1,varname="offline_text"
			}
		},
		{
			name="onLine_btn",type=1,typeName="Button",time=0,x=100,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/button.png",varname="onLine_btn",callbackfunc="onOnLineBtnClick",
			{
				name="onLine_text",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[正式]],colorA=1,varname="onLine_text"
			}
		},
		{
			name="china_btn",type=1,typeName="Button",time=0,x=200,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/button.png",varname="china_btn",callbackfunc="onChinaBtnClick",
			{
				name="china_text",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[中文]],colorA=1,varname="china_text"
			}
		},
		{
			name="yinni_btn",type=1,typeName="Button",time=0,x=300,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/button.png",varname="yinni_btn",callbackfunc="onYinniBtnClick",
			{
				name="yinni_text",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[印尼]],colorA=1,varname="yinni_text"
			}
		},
		{
			name="change_btn",type=1,typeName="Button",time=0,x=400,y=0,width=64,height=64,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,file="ui/button.png",varname="change_btn",callbackfunc="onChangeBtnClick",
			{
				name="Text23",type=4,typeName="Text",time=0,x=0,y=0,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[确定]],colorA=1
			}
		},
		{
			name="Text21",type=4,typeName="Text",time=0,x=44,y=-15,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTop,fontSize=30,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=0,string=[[亮色选中,确定后生效]],colorA=1
		},
		{
			name="check_url",type=4,typeName="Text",time=0,x=-383,y=89,width=960,height=30,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="check_url"
		}
	}
}
return login_scene;