--Created by the QnEditor,do not modify.If not,you will die very nankan!
local MAP = {
	var = {
		baseNode = 1,
		imageNode = 2,
		headImage = 3,
		View_vip = 4,
		bgButton = 5,
		sitdownImage = 6,
		infoNode = 7,
		AddGoldBtn = 8,
		AddImage = 9,
		stateLabel = 10,
		moneyLabel = 11,
		gold_icon = 12,
		giftButton = 13,
		giftCenter_node = 14,
		gift_btn_big = 15,
		small_poker_node = 16,
		poker_node = 17,
		winBorderView = 18,
		starImage1 = 19,
		starImage2 = 20,
		winnerText = 21,
		seatCenter_node = 22,
		chatBubble_node_right = 23,
		chatBubble_node_left = 24,
		seatId = 25,
	},
	ui = {
		[1] = {"baseNode"},
		[2] = {"baseNode","imageNode"},
		[3] = {"baseNode","imageNode","headImage"},
		[4] = {"baseNode","View_vip"},
		[5] = {"baseNode","bgButton"},
		[6] = {"baseNode","sitdownImage"},
		[7] = {"baseNode","infoNode"},
		[8] = {"baseNode","infoNode","AddGoldBtn"},
		[9] = {"baseNode","infoNode","AddGoldBtn","AddImage"},
		[10] = {"baseNode","infoNode","stateLabel"},
		[11] = {"baseNode","infoNode","moneyLabel"},
		[12] = {"baseNode","infoNode","gold_icon"},
		[13] = {"baseNode","giftButton"},
		[14] = {"baseNode","giftButton","giftCenter_node"},
		[15] = {"baseNode","gift_btn_big"},
		[16] = {"baseNode","small_poker_node"},
		[17] = {"baseNode","poker_node"},
		[18] = {"baseNode","winBorderView"},
		[19] = {"baseNode","winBorderView","starImage1"},
		[20] = {"baseNode","winBorderView","starImage2"},
		[21] = {"baseNode","winBorderView","winnerText"},
		[22] = {"baseNode","seatCenter_node"},
		[23] = {"baseNode","chatBubble_node_right"},
		[24] = {"baseNode","chatBubble_node_left"},
		[25] = {"seatId"},
	},
	func = {
		[5] = "onBgButtonClick",
		[8] = "OnAddGoldClick",
	},
}
return MAP;