local message_layer=
{
	name="message_layer",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="Image_bg",type=1,typeName="Image",time=0,x=0,y=0,width=710,height=517,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/common/common_pop_bg.png",varname="Image_bg",callbackfunc="onPopupBgTouch",
		{
			name="Image_bt_bg",type=1,typeName="Image",time=0,x=100,y=19,width=536,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_tab_bg.png",gridLeft=30,gridRight=30,varname="Image_bt_bg",
			{
				name="RadioButtonGroup",type=0,typeName="RadioButtonGroup",time=0,x=3,y=-1,width=518,height=58,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="RadioButtonGroup",
				{
					name="RadioButton_1",type=0,typeName="RadioButton",time=0,x=-5,y=3,width=179,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_blank.png",file2="res/common/common_tab_l.png",varname="RadioButton_1",
					{
						name="Text_l",type=4,typeName="Text",time=0,x=20,y=10,width=143,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_l",colorA=1,
						{
							name="Image_sysMsg_point",type=1,typeName="Image",time=0,x=-15,y=-17,width=24,height=26,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_sysMsg_point"
						}
					}
				},
				{
					name="RadioButton_2",type=0,typeName="RadioButton",time=0,x=177,y=3,width=174,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_blank.png",file2="res/common/common_tab_m.png",varname="RadioButton_2",
					{
						name="Text_m",type=4,typeName="Text",time=0,x=10,y=9,width=152,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_m",
						{
							name="Image_sysNotice_point",type=1,typeName="Image",time=0,x=-14,y=-15,width=24,height=26,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_sysNotice_point"
						}
					}
				},
				{
					name="RadioButton_3",type=0,typeName="RadioButton",time=0,x=355,y=3,width=179,height=57,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_blank.png",file2="res/common/common_tab_r.png",varname="RadioButton_3",
					{
						name="Text_r",type=4,typeName="Text",time=0,x=20,y=9,width=135,height=35,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_r",
						{
							name="Image_friend_point",type=1,typeName="Image",time=0,x=-13,y=-15,width=24,height=26,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_friend_point"
						}
					}
				}
			}
		},
		{
			name="Image_delete",type=1,typeName="Image",time=0,x=16,y=409,width=682,height=82,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_dialog_di2.png",gridLeft=15,gridRight=15,gridTop=10,gridBottom=20,varname="Image_delete",
			{
				name="Button_delete",type=1,typeName="Button",time=0,x=549,y=20,width=131,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_btn_yellow_s.png",gridLeft=40,gridRight=40,varname="Button_delete",
				{
					name="Text_delete",type=4,typeName="Text",time=0,x=20,y=8,width=92,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_delete"
				}
			},
			{
				name="Button_sure",type=1,typeName="Button",time=0,x=419,y=19,width=131,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_btn_yellow_s.png",gridLeft=40,gridRight=40,varname="Button_sure",
				{
					name="Text_sure",type=4,typeName="Text",time=0,x=20,y=7,width=90,height=33,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_sure"
				}
			},
			{
				name="Button_cancel",type=1,typeName="Button",time=0,x=551,y=18,width=131,height=50,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_btn_purple_s.png",gridLeft=40,gridRight=40,varname="Button_cancel",
				{
					name="Text_cancel",type=4,typeName="Text",time=0,x=21,y=9,width=90,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_cancel"
				}
			},
			{
				name="Text_tip",type=5,typeName="TextView",time=0,x=5,y=0,width=437,height=80,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignLeft,fontSize=17,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[TextView]],colorA=1,varname="Text_tip"
			}
		},
		{
			name="Text_none",type=4,typeName="Text",time=0,x=63,y=197,width=592,height=43,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_none",colorA=1
		}
	}
}
return message_layer;