local setting_feedback=
{
	name="setting_feedback",type=0,typeName="View",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignTopLeft,
	{
		name="Image_bg",type=1,typeName="Image",time=0,x=0,y=0,width=960,height=640,visible=1,fillParentWidth=1,fillParentHeight=1,nodeAlign=kAlignCenter,file="res/setting/setting_fb_bg.png",varname="Image_bg",
		{
			name="Image_line",type=1,typeName="Image",time=0,x=0,y=-275,width=13,height=85,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/setting/setting_fb_line.png",varname="Image_line"
		},
		{
			name="Text_self_service",type=4,typeName="Text",time=0,x=-242,y=-275,width=173,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=22,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="Text_self_service"
		},
		{
			name="Text_msg_board",type=4,typeName="Text",time=0,x=220,y=-275,width=173,height=66,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,fontSize=22,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_msg_board",colorA=1
		},
		{
			name="Image_fb_redPoint",type=1,typeName="Image",time=0,x=173,y=12,width=24,height=26,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopRight,file="res/common/common_red_point.png",gridLeft=12,gridRight=12,gridTop=12,gridBottom=12,varname="Image_fb_redPoint"
		},
		{
			name="Button_close",type=1,typeName="Button",time=0,x=436,y=-276,width=34,height=29,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,file="res/setting/setting_close.png",varname="Button_close"
		},
		{
			name="View_self_service",type=0,typeName="View",time=0,x=-460,y=-197,width=0,height=0,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="View_self_service",
			{
				name="ScrollView_chat",type=0,typeName="ScrollView",time=0,width=921,height=495,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="ScrollView_chat"
			}
		},
		{
			name="View_msg_board",type=0,typeName="View",time=0,x=-457,y=-217,width=0,height=0,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignCenter,varname="View_msg_board",
			{
				name="Image_fd_bg",type=1,typeName="Image",time=0,x=3,width=910,height=260,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_input.png",gridLeft=12,gridRight=12,gridTop=20,gridBottom=20,varname="Image_fd_bg",
				{
					name="Image_fd_title",type=1,typeName="Image",time=0,x=-1,y=-1,width=912,height=68,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_chat_head.png",gridLeft=6,gridRight=6,gridTop=20,gridBottom=20,varname="Image_fd_title"
				},
				{
					name="Text_type",type=4,typeName="Text",time=0,x=357,y=12,width=196,height=40,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignCenter,colorRed=133,colorGreen=134,colorBlue=134,string=[[Text]],varname="Text_type",colorA=1,
					{
						name="Image38",type=1,typeName="Image",time=0,x=-8,y=0,width=27,height=27,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignRight,file="res/setting/setting_xia.png"
					}
				},
				{
					name="EditTextView_content",type=7,typeName="EditTextView",time=0,x=33,y=70,width=839,height=90,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=18,textAlign=kAlignTopLeft,colorRed=28,colorGreen=27,colorBlue=28,colorA=1,varname="EditTextView_content"
				},
				{
					name="Button_addpic",type=1,typeName="Button",time=0,x=28,y=161,width=109,height=89,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_fb_addpic.png",varname="Button_addpic"
				},
				{
					name="Text_addpic",type=4,typeName="Text",time=0,x=138,y=203,width=100,height=36,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=22,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],colorA=1,varname="Text_addpic"
				},
				{
					name="Image_fb_pic",type=1,typeName="Image",time=0,x=28,y=160,width=109,height=89,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/common/common_blank.png",varname="Image_fb_pic"
				},
				{
					name="Image_zhankai",type=1,typeName="Image",time=0,x=2,y=66,width=908,height=202,visible=0,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_zhankai.png",gridLeft=10,gridRight=10,gridTop=10,gridBottom=15,varname="Image_zhankai",
					{
						name="RadioButtonGroup_type",type=0,typeName="RadioButtonGroup",time=0,x=0,y=5,width=909,height=187,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="RadioButtonGroup_type",
						{
							name="RadioButton1",type=0,typeName="RadioButton",time=0,x=125,y=3,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton1"
						},
						{
							name="RadioButton2",type=0,typeName="RadioButton",time=0,x=125,y=50,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton2"
						},
						{
							name="RadioButton3",type=0,typeName="RadioButton",time=0,x=125,y=98,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton3"
						},
						{
							name="RadioButton4",type=0,typeName="RadioButton",time=0,x=125,y=147,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton4"
						},
						{
							name="RadioButton5",type=0,typeName="RadioButton",time=0,x=568,y=3,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton5"
						},
						{
							name="RadioButton6",type=0,typeName="RadioButton",time=0,x=568,y=50,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton6"
						},
						{
							name="RadioButton7",type=0,typeName="RadioButton",time=0,x=568,y=98,width=35,height=38,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_unc.png",file2="res/setting/setting_c.png",varname="RadioButton7"
						}
					},
					{
						name="Text_type_1",type=4,typeName="Text",time=0,x=180,y=11,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=20,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_1",colorA=1
					},
					{
						name="Text_type_2",type=4,typeName="Text",time=0,x=180,y=55,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_2"
					},
					{
						name="Text_type_3",type=4,typeName="Text",time=0,x=180,y=105,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_3"
					},
					{
						name="Text_type_4",type=4,typeName="Text",time=0,x=180,y=153,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_4"
					},
					{
						name="Text_type_5",type=4,typeName="Text",time=0,x=618,y=11,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_5"
					},
					{
						name="Text_type_6",type=4,typeName="Text",time=0,x=618,y=55,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_6"
					},
					{
						name="Text_type_7",type=4,typeName="Text",time=0,x=618,y=105,width=125,height=31,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=24,textAlign=kAlignLeft,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_type_7"
					}
				}
			},
			{
				name="Button_commit",type=1,typeName="Button",time=0,x=343,y=264,width=221,height=69,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_commit.png",varname="Button_commit",
				{
					name="Text_commit",type=4,typeName="Text",time=0,x=31,y=10,width=161,height=47,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=26,textAlign=kAlignCenter,colorRed=255,colorGreen=255,colorBlue=255,string=[[Text]],varname="Text_commit"
				}
			},
			{
				name="Image_history_bg",type=1,typeName="Image",time=0,y=369,width=910,height=155,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,file="res/setting/setting_input.png",gridLeft=12,gridRight=12,gridTop=20,gridBottom=20,varname="Image_history_bg",x=0,
				{
					name="ScrollView_history",type=0,typeName="ScrollView",time=0,x=15,y=11,width=886,height=135,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,varname="ScrollView_history"
				},
				{
					name="Text_history",type=4,typeName="Text",time=0,x=10,y=-44,width=130,height=46,visible=1,fillParentWidth=0,fillParentHeight=0,nodeAlign=kAlignTopLeft,fontSize=18,textAlign=kAlignLeft,colorRed=28,colorGreen=27,colorBlue=28,string=[[Text]],colorA=1,varname="Text_history"
				}
			}
		}
	}
}
return setting_feedback;